### ISSUE TITLE
Ubuntu 16.04 write_project.tcl seg fault

### ISSUE THREAD

**Issue by JennySmith888** [strath-sdr/rfsoc_qpsk#14]
Hello, I have tried twice to run the build_project.tcl script as specified in the readme and both times my os has killed the process. I attached a file containing the end of the build process output, my computer memory, and os version. Is there another way I can build the project on my system or access the vivado block diagram without building it myself? P.S. I was able to successfully build the project from April 5th.
[error.log](https://github.com/strath-sdr/rfsoc_qpsk/files/3499647/error.log)

**Comment by jogomojo** [comment]
Hi Jenny,

This was due to a mistake in the `write_project.tcl` file I've fixed this in #15 

Josh
