### ISSUE TITLE
.dcp file

### ISSUE THREAD

**Issue by tanman777** [strath-sdr/rfsoc_qpsk#16]
We are working through the qpsk_tx_symbol_gen_bd.xpr and the issue stalls at DCP does not exist.

Could be related to synthesis configuration issues, but would like to see if you could share the .dcp file?

**Comment by jogomojo** [comment]
Hi tanman,

I'm really not sure what you're asking here. Are you looking at the System Generator files or the Vivado files? What is the issue you have?

Running the `make` command to build the project (as described in the readme) should produce both the main project .xpr file and the bitstream for you. All the relevant .dcp files should also be generated in this process.

If you want to look at the IP used in the Tx side then you will need to open the `AXI_QPSK_Tx.slx` file (which is located in the `rfsoc_qpsk/boards/ip/sysgen/tx` directory) using System Generator.

Josh

**Comment by tanman777** [comment]
So we have the full python version of the RFsoc_qpsk files.  We were trying to change just the amplitude values on the .bit file.  Is there a way to do this that are aware of?

**Comment by jogomojo** [comment]
Is this the same issue? There is a section of the notebook which allows you to change the transmitter gain using either code or an ipywidget slider.

**Comment by jogomojo** [comment]
closing this issue due to lack of response.

**Comment by tanman777** [comment]
I know you folks closed an old issue and maybe the times that are following might be of concern.  But this I've been waiting for different concerns to go from Vivado 18.3 to 19.2 see here.

https://github.com/strath-sdr/rfsoc_qpsk/issues

Tanay....

Tanay Bhatt, Ph.D., P.E.
214-986-2498

________________________________
