### ISSUE TITLE
SysGen and iprepo HDL out of sync

### ISSUE THREAD

**Issue by cramsay** [strath-sdr/rfsoc_qpsk#2]
Fix in PR#1 (https://github.com/strath-sdr/rfsoc_qpsk_demo/pull/1) has been applied to generated HDL only.

Can someone with SysGen access update the data inspector for the last rx "tap off"? FIFO depth should be 127, and the constant for the read threshold should be 63.

**Comment by jogomojo** [comment]
Currently, the system generator model produces a broken IP. It is being worked on.

**Comment by cramsay** [comment]
Fixed by PR #11
