### ISSUE TITLE
Can I send a custom message to the QPSK transmitter?

### ISSUE THREAD

**Issue by ArtisticZhao** [strath-sdr/rfsoc_qpsk#23]
Hello, I'm working on the ZCU111 to build a QPSK transmitter. 
I can't figure out how to send a custom message use the pynq to the hardware to do the QPSK modulation.
I also use the TCL console to create the project. But I find that there is no constraints file in the project.

**Comment by dnorthcote** [comment]
Hi Zhao,

Currently, the QPSK model doesn't have the capabilities to transmit and receive a custom message. To achieve this you will have to design an FPGA architecture that can transfer data into the QPSK transmitter chain, and then create another architecture that receives the data after the receiver chain. In addition to this, you will have to consider creating frames/packets of data. Something similar to that described in Chapter 12 of this book: [https://www.desktopsdr.com/]

You shouldn't need a TCL file for location constraints. The location constraints for the RF-Data converter are automatically generated. You should be able to create the Vivado project and generate a bitstream when running the project setup scripts.

Kind Regards,
David.
