### ISSUE TITLE
Symbol Timing Synchronisation

### ISSUE THREAD

**Issue by dnorthcote** [strath-sdr/rfsoc_qpsk#24]
This issue concerns the system generator model named _axi_qpsk_rx_tsync.slx_.

The timing synchronization mask implements the PLL filter coefficients in accordance with equations (7.30) and (7.31) on pages 267 and 268 in [1].

The first coefficient is generated correctly, however, the second is off slightly due to a missing bracket in the "Timing Sync" block mask.

Currently used code: `Kb = (4*(BnS*Ts)^2)/(Kn*Ks*(d+1/4*d)^2);` 

Corrected code: `Kb = (4*(BnS*Ts)^2)/(Kn*Ks*(d+1/(4*d))^2); `

This leads to a very small gain error that may lead to desynchronization problems. Further analysis and testing are required to check timing synchronization with corrected gains.

[1] — R. W. Stewart, K. Barlee, D. S. W. Atkinson, and L. H. Crockett, _Software Defined Radio using MATLAB & Simulink and the RTL-SDR_, Published by Strathclyde Academic Media, 2015.

**Comment by cramsay** [comment]
Thanks for the issue --- that's a *very* good spot!

Fixed in PR #26
