### ISSUE TITLE
Error using Voila notebook

### ISSUE THREAD

**Issue by FrancoCapraro** [strath-sdr/rfsoc_qpsk#34]
Hello. I installed voila as you mention [https://strath-sdr.github.io/pynq/linux/zynq/fpga/voila/2021/02/22/install-voila-on-pynq-v2-6.html](url).
After i run in a command line:

voila /home/xilinx/jupyter_notebooks/qpsk-demonstrator/voila_rfsoc_qpsk_demonstrator.ipynb --ExecutePreprocessor.timeout=180 --theme=dark --port=8866 --TagRemovePreprocessor.remove_cell_tags='{"ignore_me"}'

Then open new browser tab and enter the following into the address bar: http://board_ip_address:8866 but i get:

![image](https://user-images.githubusercontent.com/37583249/109669489-6d968000-7b72-11eb-8c21-a6563ce358dc.png)

![image](https://user-images.githubusercontent.com/37583249/109669567-81da7d00-7b72-11eb-87f3-f93eca3f5f06.png)

**Comment by dnorthcote** [comment]
Hi Franco,

Thanks for using the Voila demonstration. It appears that Voila is correctly installed on your system. However, I suspect the QPSK package needs to be reinstalled/upgraded. Can you run the code cell below in the Jupyter terminal. Ensure all notebook kernels are shutdown first.

```sh
pip3 install --force-reinstall --no-deps git+https://github.com/strath-sdr/rfsoc_qpsk
```

After you run the above command, you're version of rfsoc-qpsk should be upgraded to v1.3. Let me know if this works and I can support further if there any additional issues,

Thanks,
David.

**Comment by dnorthcote** [comment]
Just an additional note: if Voila was previously ran on port 8866, you will need to increment the port to 8867. Alternatively, you can just reset your development board and use port 8866 again.

**Comment by FrancoCapraro** [comment]
Fixed !now is working ,Thank you so much!
