### ISSUE TITLE
The constraints files of ZCU111 is empty

### ISSUE THREAD

**Issue by LargeDumpling** [strath-sdr/rfsoc_qpsk#42]
The "constraints.xdc" under "rfsoc_qpsk/boards/ZCU111/rfsoc_qpsk/" is an empty file.

**Comment by dnorthcote** [comment]
Hi @LargeDumpling,

This is to be expected. We used the same make recipe for all boards, meaning an empty constraints file is necessary for the ZCU111 board.

We did have the idea of merging the make recipe together for each board. Hence why an empty constraints file has been left in the ZCU111 folder.

It won't impact the design in any way. I'll close this issue,

Thanks,
David.
