### ISSUE TITLE
Error in reading bitstream file and hwh file in qpsk overlay

### ISSUE THREAD

**Issue by Qw1chen** [strath-sdr/rfsoc_qpsk#46]
I used the commands make block_design and make bitstream to generate the .bit and .hwh files for the ZCU216 board. The files were successfully generated and are located at:

.bit file: block_design.runs/impl_1/rfsoc_qpsk_wrapper.bit
.hwh file: block_design.gen/sources_1/bd/rfsoc_qpsk/hw_handoff/rfsoc_qpsk.hwh
I uploaded these files to a Jupyter notebook and followed the instructions in the 02_rfsoc_qpsk_demonstrator.ipynb notebook. However, after executing the command ol = QpskOverlay(), the Jupyter notebook shut down and I lost connection to the Jupyter Lab over Ethernet.

Could you help identify any missing steps or errors in the process before loading the bitstream onto the board?

**Comment by Qw1chen** [comment]
No,I did not get any error message when I import qpskoverlay, so I guess I
import the function successfully.

Andrew Maclellan ***@***.***>於 2024年5月24日 週五，21:19寫道：

**Comment by Qw1chen** [comment]
I use the prebuilt image posted here (https://discuss.pynq.io/t/the-rfsoc-book-and-design-examples-for-the-zcu208-zcu216-development-boards/5613) and it is built by Sara Susan. The version is Pynq v2.7.

I use from rfsoc_qpsk.qpsk_overlay import QpskOverlay to interface with the bitstream, and the setup of the zcu216 is picture below:
![Uploading IMG_3151.jpg…]()

thanks!

**Comment by axdy** [comment]
Excellent, that image should be fine. Unfortunately, the link you sent is a dead, but you could try the following in the meantime while you reupload the picture:
```python
from pynq.overlay import Overlay
ol = Overlay('bistream_name.bit')
ol?
```
This is using PYNQ's default overlay class that is used by the QPSKOverlay class. Can you see the list of IP's produced by `ol?`.

**Comment by Qw1chen** [comment]
The setup picture:
![IMG_3151](https://github.com/strath-sdr/rfsoc_qpsk/assets/120239501/dba4f1f4-1011-450f-bcfc-7e90f952d31c)
and using the Overlay, I can see the list if IP:
![Screenshot 2024-05-24 112702](https://github.com/strath-sdr/rfsoc_qpsk/assets/120239501/eff5fb51-a35d-4056-bb3c-e3ee064fb7ee)

thanks!

**Comment by axdy** [comment]
Everything seems to be setup correctly for the CLK104 board and the overlay sees the IPs in the bitstream which is good. 
To rule out the bitstream location being an error could you:
```python
ol = QpskOverlay(bitfile_name='bitstreamname.bit')
```
in the original notebook. Otherwise, I'll have to give this a try on my end and may take longer to get back to you.

**Comment by axdy** [comment]
So i just tried loading the overlay on the ZCU216 using the [Release v1.4.5](https://github.com/strath-sdr/rfsoc_qpsk/releases/tag/v1.4.5) and it loads the bitstream on my end. If you want to try installing the repo through the Release via the README.md instructions and confirm if it works for you.
Shortened instructions: (please run them in the terminal in the Jupyter instance running on the ZCU216.)
```bash
pip3 install https://github.com/strath-sdr/rfsoc_qpsk/releases/download/v1.4.5/rfsoc_qpsk.tar.gz
python -m rfsoc_qpsk install
```

**Comment by axdy** [comment]
I just tried commenting out the `init_clocks()` function in the `QpskOverlay()` and it seems if the clocks don't get initialised properly the board crashes. So maybe keep this in mind.

**Comment by Qw1chen** [comment]
Yes!, I find out I ran the code 'ol = QpskOverlay(init_rf_clks=False)' and it caused the board shut down, and after I use the 'ol=QpskOverlay()', it can work! 

Thank you very much!
