### ISSUE TITLE
DMA access problem

### ISSUE THREAD

**Issue by Qw1chen** [strath-sdr/rfsoc_qpsk#47]
I'm reimplementing the QPSK transceiver and need to change the DAC and ADC clock values. I've removed the interpolate and decimate modules and replaced them with an AXI interconnect. However, now when I try to access the DMA using tx_ch0 = ol.qpsk_tx.axi_dma_0.sendchannel, the board crashes. I've been stuck on this issue for several days and can't figure out what the problem is. Can you help?

![image](https://github.com/strath-sdr/rfsoc_qpsk/assets/120239501/e4b08b4a-9102-4936-a2dc-7ec0dd10e2b5)
![image](https://github.com/strath-sdr/rfsoc_qpsk/assets/120239501/83d6688c-8f93-45ff-bec1-4dfcabf4eed5)
![image](https://github.com/strath-sdr/rfsoc_qpsk/assets/120239501/b2329926-0c8f-497b-bdbe-4d6edf180769)
If you need design to figure out the problem, the link is:
https://drive.google.com/file/d/1_F2dnBlpuOJDBUTIe2o9Da3YWPtihrWC/view?usp=sharing
Thank you very much!

**Comment by axdy** [comment]
Hi there,

Apologies for the delayed reply.

Could you elaborate why you need to remove the decimation and interpolation filters? Removing these and replacing them with an interconnect will not work and it will very likely crash the board since the dma's will no longer receive a tlast signal. 

If you would like to change the clock rates of the design I would suggest editing the simulink models in `boards/ip/sysgen` and ensuring a simulation of your changes works before changing the Vivado block design.

Regards,
Andrew

**Comment by Qw1chen** [comment]
hi,
I removed interpolation and decimation to use the RF data converter bypass mode. I added a tlast signal, and now I can receive a signal. However, I'm encountering a discrepancy: the amplitude of the real part received in the ADC is different from that of the imaginary part. Do you know the reason for this?
the weird resule is below:
![image](https://github.com/strath-sdr/rfsoc_qpsk/assets/120239501/74b98ae6-ee5e-48c5-84a9-ee15c2ba26cc)
![image](https://github.com/strath-sdr/rfsoc_qpsk/assets/120239501/695a1289-e837-4996-b0dd-bff403d6d6a8)
Thank you!

**Comment by axdy** [comment]
Hi there,

This is likely due to the phase offset incurred during transmission and reception. You can adjust the transmitting and receiving the phase offset by altering the `MixerSettings['PhaseOffset']` variable for either the `adc_block` or `dac_block`. 

Hope that helps,
Andrew

**Comment by Qw1chen** [comment]
Can I ask why the phase offset between the transmitter and receiver causes amplitude degradation? 
So if I perform phase calibration, can I avoid this effect?

Thank you very much!
This helps a lot!
