### ISSUE TITLE
Demo QPSK wirelessly 

### ISSUE THREAD

**Issue by Shashilaksha** [strath-sdr/rfsoc_qpsk#49]
I worked with QPSK demo. Now I need to develop this as wireless without loopback conncetion. But then it does not configure. Could you have any experience like doing this as wireless

**Comment by axdy** [comment]
The QPSK demo should work wirelessly on the RFSoC. A bandpass filter is required between the antennas and the RFADCs/DACs to stop the signal leaking to other bit of the spectrum and receiving unwanted signals. Please keep in mind that the RFSoC won't amplify the signal by much so the antennas would need to be relatively close.

**Comment by axdy** [comment]
Closing for now, should you have any other questions please comment.

**Comment by Shashilaksha** [comment]
Thank you for reply. i am working with that. but synchronous fail  in wirelessly. That is the issue.
